// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7-dsPybRxMmfsxaz2XILDsHlus11MuRQ',
    appId: '1:781264826386:web:ed08d7f85ac8468ecd28cb',
    messagingSenderId: '781264826386',
    projectId: 'tcratinventory',
    authDomain: 'tcratinventory.firebaseapp.com',
    storageBucket: 'tcratinventory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGw9hWCXobM-yzMZHek2QxpH7P258F1Vw',
    appId: '1:781264826386:android:e151b6bab88d4f53cd28cb',
    messagingSenderId: '781264826386',
    projectId: 'tcratinventory',
    storageBucket: 'tcratinventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOA_4Zvgur2Z9WGj8lfXZJu2J67L-3rs',
    appId: '1:781264826386:ios:0bd01feaceb6e5c0cd28cb',
    messagingSenderId: '781264826386',
    projectId: 'tcratinventory',
    storageBucket: 'tcratinventory.firebasestorage.app',
    iosBundleId: 'com.ttctechnocrat.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOA_4Zvgur2Z9WGj8lfXZJu2J67L-3rs',
    appId: '1:781264826386:ios:0bd01feaceb6e5c0cd28cb',
    messagingSenderId: '781264826386',
    projectId: 'tcratinventory',
    storageBucket: 'tcratinventory.firebasestorage.app',
    iosBundleId: 'com.ttctechnocrat.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7-dsPybRxMmfsxaz2XILDsHlus11MuRQ',
    appId: '1:781264826386:web:d116ea07bfb7d234cd28cb',
    messagingSenderId: '781264826386',
    projectId: 'tcratinventory',
    authDomain: 'tcratinventory.firebaseapp.com',
    storageBucket: 'tcratinventory.firebasestorage.app',
  );
}
